import uuid'
import logging'
from starlette.types import ASGIApp, Receive, Scope, Send'
'
logger = logging.getLogger("app.middleware")'
'
class RequestIDMiddleware:'
    """Pure ASGI middleware to assign a unique Request ID to every request."""'
    def __init__(self, app: ASGIApp):'
        self.app = app'
'
    async def __call__(self, scope: Scope, receive: Receive, send: Send):'
        if scope["type"] != "http":'
            await self.app(scope, receive, send)'
            return'
'
        # Extract or generate Request ID'
        headers = dict(scope.get("headers", []))'
'
        # Helper to get header value from bytes'
        def get_header(name):'
            val = headers.get(name.lower().encode())'
            return val.decode() if val else None'
'
        request_id = ('
            get_header("X-Request-ID")'
            or get_header("X-Correlation-ID")'
            or str(uuid.uuid4())'
        )'
'
        # Store in scope state for downstream access'
        if "state" not in scope:'
            scope["state"] = {}'
        scope["state"]["request_id"] = request_id'
'
        async def send_wrapper(message):'
            if message["type"] == "http.response.start":'
                resp_headers = list(message.get("headers", []))'
                resp_headers.append((b"x-request-id", request_id.encode()))'
                resp_headers.append((b"x-correlation-id", request_id.encode()))'
                message["headers"] = resp_headers'
            await send(message)'
'
        try:'
            await self.app(scope, receive, send_wrapper)'
        except Exception as exc:'
            # Propagate the exception, it will be handled by the global exception handler'
            raise exc'
