import json'
import os'
import re'
from datetime import datetime, timezone, timedelta'
from typing import Any, Dict, Optional, List'
from sqlalchemy import select, insert, update'
from app.db.database import AsyncSessionLocal'
from app.modules.ai.models import AIInsight'
'
# Cached insights older than this are treated as stale and regenerated'
CACHE_TTL_HOURS = 6'
'
PROVIDERS = ("gemini", "claude", "grok", "openai")'
PROVIDER_LABELS = {'
    "gemini": "Google Gemini",'
    "claude": "Anthropic Claude",'
    "grok": "xAI Grok",'
    "openai": "OpenAI GPT",'
}'
'
def _safe_match_id(match_id: int) -> str:'
    return re.sub(r"[^0-9]", "", str(match_id))'
'
def _as_probability(value: Any, fallback: Optional[float] = None) -> Optional[float]:'
    if value is None:'
        return fallback'
    try:'
        numeric = float(value)'
        if numeric > 1:'
            numeric = numeric / 100'
        return max(0.0, min(1.0, numeric))'
    except Exception:'
        return fallback'
'
def normalize_provider_insight(source: str, payload: Dict[str, Any], defaults: Optional[Dict[str, float]] = None) -> Dict[str, Any]:'
    defaults = defaults or {}'
    source = str(source).lower().strip()'
    home_prob = _as_probability(payload.get("home_prob", payload.get("home")), defaults.get("home_prob"))'
    draw_prob = _as_probability(payload.get("draw_prob", payload.get("draw")), defaults.get("draw_prob"))'
    away_prob = _as_probability(payload.get("away_prob", payload.get("away")), defaults.get("away_prob"))'
    confidence = _as_probability(payload.get("confidence"), defaults.get("confidence", 0.7))'
    risk_level = str(payload.get("risk_level") or payload.get("risk") or "MEDIUM").upper()'
    if risk_level not in {"LOW", "MEDIUM", "HIGH"}:'
        risk_level = "MEDIUM"'
'
    return {'
        "available": True,'
        "source": source,'
        "label": payload.get("label") or PROVIDER_LABELS.get(source, source.title()),'
        "home_prob": home_prob,'
        "draw_prob": draw_prob,'
        "away_prob": away_prob,'
        "confidence": confidence,'
        "summary": payload.get("summary") or payload.get("analysis") or "",'
        "key_factors": payload.get("key_factors") or payload.get("factors") or [],'
        "value_assessment": payload.get("value_assessment") or payload.get("value") or "",'
        "risk_level": risk_level,'
        "insight_tags": payload.get("insight_tags") or payload.get("tags") or [],'
        "error": None,'
        "from_cache": True,'
    }'
'
def _extract_insights(raw: Dict[str, Any]) -> Dict[str, Dict[str, Any]]:'
    candidates = raw.get("insights") or raw.get("agents") or raw.get("results") or raw.get("providers") or raw'
    if not isinstance(candidates, dict):'
        return {}'
'
    extracted = {}'
    for source in PROVIDERS:'
        value = candidates.get(source)'
        if isinstance(value, dict):'
            extracted[source] = value'
    return extracted'
'
async def save_match_insights(match_id: int, raw: Dict[str, Any]) -> Dict[str, Any]:'
    insights = _extract_insights(raw)'
    if not insights:'
        # If raw itself IS the insight dict'
        if all(isinstance(v, dict) for v in raw.values()) and any(k in PROVIDERS for k in raw.keys()):'
            insights = {k: v for k, v in raw.items() if k in PROVIDERS}'
        else:'
            raise ValueError("JSON must include insights for at least one provider: gemini, claude, grok, or openai")'
'
    async with AsyncSessionLocal() as db:'
        q = await db.execute(select(AIInsight).where(AIInsight.match_id == match_id))'
        existing = q.scalar_one_or_none()'
'
        if existing:'
            current = dict(existing.insights or {})'
            current.update(insights)'
            existing.insights = current'
            existing.original = raw'
            existing.uploaded_at = datetime.now(timezone.utc)'
        else:'
            new_insight = AIInsight('
                match_id=match_id,'
                insights=insights,'
                original=raw,'
                uploaded_at=datetime.now(timezone.utc)'
            )'
            db.add(new_insight)'
'
        await db.commit()'
'
    return {"match_id": match_id, "sources": sorted(insights.keys()), "count": len(insights)}'
'
def _is_stale(uploaded_at: datetime) -> bool:'
    if not uploaded_at:'
        return True'
    if uploaded_at.tzinfo is None:'
        uploaded_at = uploaded_at.replace(tzinfo=timezone.utc)'
    age = datetime.now(timezone.utc) - uploaded_at'
    return age > timedelta(hours=CACHE_TTL_HOURS)'
'
async def load_match_insights(match_id: int, defaults: Optional[Dict[str, float]] = None) -> Dict[str, Dict[str, Any]]:'
    async with AsyncSessionLocal() as db:'
        q = await db.execute(select(AIInsight).where(AIInsight.match_id == match_id))'
        row = q.scalar_one_or_none()'
'
    if not row:'
        return {}'
'
    if _is_stale(row.uploaded_at):'
        return {}'
'
    insights = row.insights'
    return {'
        source: normalize_provider_insight(source, payload, defaults=defaults)'
        for source, payload in insights.items()'
    }'
'
def infer_match_id(raw: Dict[str, Any]) -> Optional[int]:'
    value = raw.get("match_id") or raw.get("id")'
    try:'
        return int(value) if value is not None else None'
    except Exception:'
        return None'
