"""app/services/gemini_chat.py — Conversational Gemini wrapper for the in-app AI Assistant."""

import logging
import os
from typing import List, Dict, Optional

import httpx

logger = logging.getLogger(__name__)

_GEMINI_BASE = "https://generativelanguage.googleapis.com/v1beta/models"
_GEMINI_CHAT_MODELS = [
    "gemini-2.0-flash",
    "gemini-2.0-flash-lite",
    "gemini-1.5-flash-latest",
    "gemini-1.5-flash",
]

SYSTEM_PROMPT = (
    "You are VIT Assistant, the in-app sports-betting copilot for the VIT Sports "
    "Intelligence Network — an institutional-grade football prediction platform. "
    "\n\n"
    "LIVE DATA AVAILABLE ON THIS PLATFORM:\n"
    "- Real upcoming fixtures: pulled live from TheSportsDB (18 leagues, 90-day window), "
    "updated every 3 hours. Users can see them on the Matches page.\n"
    "- Live match odds: streamed via The Odds API from 40+ bookmakers with CLV tracking.\n"
    "- Team news & injuries: fetched via DuckDuckGo web search and injected into every "
    "prediction request automatically — no manual input needed.\n"
    "- xG, form, H2H stats: computed by the SCIE (Self-Contained Intelligence Engine) "
    "from the historical match database (6+ months of real results).\n"
    "- AI predictions: generated by a 13-model ensemble (Random Forest, XGBoost, "
    "LightGBM, Neural Net, Poisson, Elo, and more) trained on real historical data.\n"
    "- Market movement & CLV: tracked per-prediction via The Odds API.\n"
    "\n"
    "WHAT TO TELL USERS:\n"
    "When a user asks about live data, upcoming matches, team news, injuries, or odds, "
    "ALWAYS direct them to the relevant page on this platform — do NOT say you lack "
    "real-time access. This platform IS connected to live data sources.\n"
    "- Upcoming matches → Matches page (updated every 3 hours from TheSportsDB)\n"
    "- Predictions with live context → run a prediction via the Predict page\n"
    "- Odds & CLV → Odds Compare or the prediction detail page\n"
    "- Model performance → Model Performance dashboard\n"
    "- Bankroll advice → Bankroll page (Kelly criterion calculator built in)\n"
    "\n"
    "Help users understand platform features (predictions, ML models, ROI/CLV analytics, "
    "accumulator builder, trust system, validator network, governance, wallet, training "
    "pipeline, AI insights, KYC, subscriptions, developer API). Keep responses concise, "
    "conversational, and actionable. Never guarantee bet outcomes or give financial advice; "
    "always note that betting carries risk."
)


def _no_key_response() -> Dict:
    return {
        "available": False,
        "reply": (
            "The AI Assistant is not configured yet. An admin needs to add a "
            "GEMINI_API_KEY in **Admin → API Keys** to enable conversational "
            "responses."
        ),
        "error": "GEMINI_API_KEY not configured",
    }


def _build_contents(history: List[Dict[str, str]], message: str) -> List[Dict]:
    """Convert chat history + new user message into Gemini's `contents` format.

    Each history item is {role: "user"|"assistant", content: "..."}.
    Gemini expects role values "user" and "model".
    """
    contents: List[Dict] = []
    for turn in history[-12:]:  # cap context window
        role = "user" if turn.get("role") == "user" else "model"
        text = (turn.get("content") or "").strip()
        if not text:
            continue
        contents.append({"role": role, "parts": [{"text": text}]})

    contents.append({"role": "user", "parts": [{"text": message.strip()}]})
    return contents


async def chat(
    message: str,
    history: Optional[List[Dict[str, str]]] = None,
    context: Optional[str] = None,
) -> Dict:
    """Send a chat turn to Gemini and return the assistant reply.

    Args:
        message: the new user message.
        history: prior conversation [{role, content}, ...] (optional).
        context: extra system context to inject (e.g., current page or match).

    Returns:
        {"available": bool, "reply": str, "error": str|None}
    """
    api_key = os.getenv("GEMINI_API_KEY", "").strip()
    if not api_key:
        return _no_key_response()

    if not message or not message.strip():
        return {"available": True, "reply": "Please enter a question.", "error": None}

    system_text = SYSTEM_PROMPT
    if context:
        system_text += f"\n\nAdditional context for this conversation:\n{context.strip()}"

    payload = {
        "systemInstruction": {"parts": [{"text": system_text}]},
        "contents": _build_contents(history or [], message),
        "generationConfig": {
            "temperature": 0.5,
            "maxOutputTokens": 800,
        },
    }

    try:
        resp = None
        async with httpx.AsyncClient(timeout=25) as client:
            for model in _GEMINI_CHAT_MODELS:
                url = f"{_GEMINI_BASE}/{model}:generateContent?key={api_key}"
                resp = await client.post(
                    url,
                    json=payload,
                    headers={"Content-Type": "application/json"},
                )
                if resp.status_code not in (404, 503):
                    break
                logger.debug("[gemini-chat] model %s unavailable (%s), trying next", model, resp.status_code)

        if resp.status_code in (401, 403):
            return {
                "available": False,
                "reply": "The configured Gemini API key was rejected. Please update it in Admin → API Keys.",
                "error": "Invalid Gemini API key",
            }
        if resp.status_code == 429:
            return {
                "available": False,
                "reply": "The AI Assistant is rate-limited right now. Please try again in a few seconds.",
                "error": "Rate limit reached",
            }
        if not resp.is_success:
            return {
                "available": False,
                "reply": f"Gemini returned an error (HTTP {resp.status_code}). Please try again later.",
                "error": f"HTTP {resp.status_code}",
            }

        data = resp.json()
        candidates = data.get("candidates") or []
        if not candidates:
            return {
                "available": True,
                "reply": "The model didn't produce a response. Try rephrasing your question.",
                "error": None,
            }

        parts = candidates[0].get("content", {}).get("parts", [])
        reply_text = "".join(p.get("text", "") for p in parts).strip()
        if not reply_text:
            reply_text = "The model didn't produce a response. Try rephrasing your question."

        return {"available": True, "reply": reply_text, "error": None}

    except httpx.TimeoutException:
        return {
            "available": False,
            "reply": "The AI Assistant timed out. Please try a shorter question or try again.",
            "error": "Timeout",
        }
    except Exception as exc:
        logger.error(f"Gemini chat error: {exc}")
        return {
            "available": False,
            "reply": "Something went wrong talking to the AI Assistant. Please try again.",
            "error": str(exc),
        }
