import { Brain, X, ShieldCheck, BarChart2, AlertTriangle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogTitle } from "@/components/ui/dialog";
import { useEffect, useState } from "react";

interface PlatformNoticeProps {
  isOpen?: boolean;
  onClose?: () => void;
  showOnce?: boolean;
}

/**
 * PlatformNotice — Analytics platform disclaimer.
 * Replaces gambling disclaimer; this is an intelligence/analytics product.
 * Shows once per session, stored in localStorage.
 */
export function GamblingAgeDisclaimer({
  isOpen = true,
  onClose,
  showOnce = true,
}: PlatformNoticeProps) {
  const [open, setOpen] = useState(false);

  useEffect(() => {
    if (!showOnce) {
      setOpen(isOpen);
      return;
    }
    const stored = localStorage.getItem("platform_notice_shown");
    const today = new Date().toDateString();
    if (stored !== today) {
      setOpen(true);
      localStorage.setItem("platform_notice_shown", today);
    }
  }, [isOpen, showOnce]);

  const handleDismiss = () => {
    setOpen(false);
    onClose?.();
  };

  return (
    <Dialog open={open} onOpenChange={handleDismiss}>
      <DialogContent className="max-w-md border-primary/20 bg-card p-0 overflow-hidden gap-0">

        {/* Header */}
        <div className="flex items-center justify-between px-5 pt-5 pb-4 border-b border-border">
          <DialogTitle className="flex items-center gap-2.5 text-base font-bold text-foreground">
            <div className="w-8 h-8 rounded-lg bg-primary/10 border border-primary/20 flex items-center justify-center">
              <Brain size={16} className="text-primary" />
            </div>
            VIT Network — Analytics Platform
          </DialogTitle>
          {/* Prominent close button */}
          <button
            onClick={handleDismiss}
            className="w-8 h-8 rounded-lg flex items-center justify-center text-muted-foreground hover:text-foreground hover:bg-muted transition-colors"
            aria-label="Close"
          >
            <X size={16} />
          </button>
        </div>

        <div className="px-5 py-4 space-y-3 text-sm">

          {/* Core statement */}
          <div className="flex gap-3 p-3 rounded-lg bg-primary/8 border border-primary/20">
            <ShieldCheck size={16} className="text-primary flex-shrink-0 mt-0.5" />
            <p className="text-foreground/90 leading-relaxed text-xs">
              VIT Network is a <span className="font-semibold text-primary">predictive analytics and intelligence platform</span>.
              We do not operate a gambling or wagering service. All signals and predictions are informational outputs from our AI ensemble — not financial or betting advice.
            </p>
          </div>

          {/* Points */}
          <div className="space-y-2">
            {[
              { icon: BarChart2, text: "Signals are generated by a 13-model AI ensemble for research and analysis purposes only." },
              { icon: ShieldCheck, text: "No real money is staked on this platform. VITCoin is an internal utility token." },
              { icon: AlertTriangle, text: "All analytics outputs are probabilistic estimates — not guaranteed outcomes. Use your own judgment." },
            ].map(({ icon: Icon, text }, i) => (
              <div key={i} className="flex gap-2.5 items-start">
                <Icon size={13} className="text-muted-foreground flex-shrink-0 mt-0.5" />
                <p className="text-xs text-muted-foreground leading-relaxed">{text}</p>
              </div>
            ))}
          </div>

          <p className="text-[10px] text-muted-foreground/60 font-mono leading-relaxed border-t border-border pt-3">
            By continuing you acknowledge these terms. View our{" "}
            <a href="/policy" className="text-primary hover:underline">Privacy Policy</a>
            {" "}and{" "}
            <a href="/policy" className="text-primary hover:underline">Terms of Service</a>.
          </p>
        </div>

        {/* Footer CTA */}
        <div className="px-5 pb-5">
          <Button
            onClick={handleDismiss}
            className="w-full font-mono font-bold tracking-wide"
          >
            I Understand — Enter Platform
          </Button>
        </div>

      </DialogContent>
    </Dialog>
  );
}

export default GamblingAgeDisclaimer;
