# alembic/script.py.mako
"""add reward tables

Revision ID: 1ea9f5fca66d
Revises: 71b62dcde5da
Create Date: 2026-04-25 18:41:17.970824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ea9f5fca66d'
down_revision: Union[str, None] = '71b62dcde5da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offer_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('reward_type', sa.String(length=30), nullable=False),
    sa.Column('provider_offer_id', sa.String(length=128), nullable=True),
    sa.Column('provider_event_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('reward_margin', sa.Float(), nullable=False),
    sa.Column('wallet_tx_id', sa.String(length=36), nullable=True),
    sa.Column('provider_payload', sa.JSON(), nullable=False),
    sa.Column('provider_payload_hash', sa.String(length=128), nullable=False),
    sa.Column('provider_signature', sa.String(length=255), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_payload_hash', name='uq_offer_completions_provider_payload')
    )
    op.create_index('idx_offer_completions_status', 'offer_completions', ['status'], unique=False)
    op.create_index(op.f('ix_offer_completions_id'), 'offer_completions', ['id'], unique=False)
    op.create_index(op.f('ix_offer_completions_provider'), 'offer_completions', ['provider'], unique=False)
    op.create_index(op.f('ix_offer_completions_provider_event_id'), 'offer_completions', ['provider_event_id'], unique=False)
    op.create_index(op.f('ix_offer_completions_status'), 'offer_completions', ['status'], unique=False)
    op.create_index(op.f('ix_offer_completions_user_id'), 'offer_completions', ['user_id'], unique=False)
    op.create_table('postback_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_completion_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('headers', sa.JSON(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('payload_hash', sa.String(length=128), nullable=False),
    sa.Column('signature', sa.String(length=255), nullable=True),
    sa.Column('validation_status', sa.String(length=30), nullable=False),
    sa.Column('validation_details', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['offer_completion_id'], ['offer_completions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_postback_audit_logs_id'), 'postback_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_postback_audit_logs_offer_completion_id'), 'postback_audit_logs', ['offer_completion_id'], unique=False)
    op.create_index(op.f('ix_postback_audit_logs_provider'), 'postback_audit_logs', ['provider'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_postback_audit_logs_provider'), table_name='postback_audit_logs')
    op.drop_index(op.f('ix_postback_audit_logs_offer_completion_id'), table_name='postback_audit_logs')
    op.drop_index(op.f('ix_postback_audit_logs_id'), table_name='postback_audit_logs')
    op.drop_table('postback_audit_logs')
    op.drop_index(op.f('ix_offer_completions_user_id'), table_name='offer_completions')
    op.drop_index(op.f('ix_offer_completions_status'), table_name='offer_completions')
    op.drop_index(op.f('ix_offer_completions_provider_event_id'), table_name='offer_completions')
    op.drop_index(op.f('ix_offer_completions_provider'), table_name='offer_completions')
    op.drop_index(op.f('ix_offer_completions_id'), table_name='offer_completions')
    op.drop_index('idx_offer_completions_status', table_name='offer_completions')
    op.drop_table('offer_completions')
    # ### end Alembic commands ###