# alembic/script.py.mako
"""add_remaining_module_tables

Revision ID: 22c85e91a8d9
Revises: 003
Create Date: 2026-04-18 07:25:21.809285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22c85e91a8d9'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_prediction_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.String(length=128), nullable=False),
    sa.Column('home_team', sa.String(length=128), nullable=True),
    sa.Column('away_team', sa.String(length=128), nullable=True),
    sa.Column('home_prob', sa.Float(), nullable=False),
    sa.Column('draw_prob', sa.Float(), nullable=False),
    sa.Column('away_prob', sa.Float(), nullable=False),
    sa.Column('over_25_prob', sa.Float(), nullable=True),
    sa.Column('btts_prob', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('model_agreement', sa.Float(), nullable=True),
    sa.Column('individual_results', sa.JSON(), nullable=True),
    sa.Column('weights_snapshot', sa.JSON(), nullable=True),
    sa.Column('pkl_models_active', sa.Integer(), nullable=True),
    sa.Column('triggered_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_prediction_audit_id'), 'ai_prediction_audit', ['id'], unique=False)
    op.create_index(op.f('ix_ai_prediction_audit_match_id'), 'ai_prediction_audit', ['match_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=True),
    sa.Column('resource', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_action', 'audit_logs', ['action'], unique=False)
    op.create_index('idx_audit_actor', 'audit_logs', ['actor'], unique=False)
    op.create_index('idx_audit_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('bankroll_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('initial_balance', sa.Float(), nullable=True),
    sa.Column('current_balance', sa.Float(), nullable=True),
    sa.Column('peak_balance', sa.Float(), nullable=True),
    sa.Column('total_staked', sa.Float(), nullable=True),
    sa.Column('total_profit', sa.Float(), nullable=True),
    sa.Column('total_bets', sa.Integer(), nullable=True),
    sa.Column('winning_bets', sa.Integer(), nullable=True),
    sa.Column('losing_bets', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bankroll_states_id'), 'bankroll_states', ['id'], unique=False)
    op.create_table('bridge_pools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_from', sa.String(length=16), nullable=False),
    sa.Column('asset_to', sa.String(length=16), nullable=False),
    sa.Column('chain_from', sa.String(length=32), nullable=False),
    sa.Column('chain_to', sa.String(length=32), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('fee_pct', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('min_amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('max_amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('pool_liquidity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bridge_pool_assets', 'bridge_pools', ['asset_from', 'asset_to'], unique=False)
    op.create_index(op.f('ix_bridge_pools_id'), 'bridge_pools', ['id'], unique=False)
    op.create_table('consensus_predictions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('match_id', sa.String(length=100), nullable=False),
    sa.Column('match_data', sa.JSON(), nullable=True),
    sa.Column('ai_p_home', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('ai_p_draw', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('ai_p_away', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('ai_confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('ai_risk', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('validator_count', sa.Integer(), nullable=False),
    sa.Column('consensus_p_home', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('consensus_p_draw', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('consensus_p_away', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('final_p_home', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('final_p_draw', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('final_p_away', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('total_influence', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id')
    )
    op.create_index('idx_consensus_match_id', 'consensus_predictions', ['match_id'], unique=False)
    op.create_index('idx_consensus_status', 'consensus_predictions', ['status'], unique=False)
    op.create_table('decision_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('prediction_id', sa.Integer(), nullable=True),
    sa.Column('decision_type', sa.String(), nullable=True),
    sa.Column('stake', sa.Float(), nullable=True),
    sa.Column('odds', sa.Float(), nullable=True),
    sa.Column('edge', sa.Float(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('model_contributions', sa.Text(), nullable=True),
    sa.Column('market_context', sa.Text(), nullable=True),
    sa.Column('bankroll_state', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_decision_logs_match', 'decision_logs', ['match_id'], unique=False)
    op.create_index(op.f('ix_decision_logs_id'), 'decision_logs', ['id'], unique=False)
    op.create_index(op.f('ix_decision_logs_match_id'), 'decision_logs', ['match_id'], unique=False)
    op.create_index(op.f('ix_decision_logs_prediction_id'), 'decision_logs', ['prediction_id'], unique=False)
    op.create_table('dev_api_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('rate_limit_rpm', sa.Integer(), nullable=False),
    sa.Column('rate_limit_rpd', sa.Integer(), nullable=False),
    sa.Column('price_vitcoin_per_1k', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_dev_api_plans_id'), 'dev_api_plans', ['id'], unique=False)
    op.create_table('match_feature_store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('home_team', sa.String(), nullable=False),
    sa.Column('away_team', sa.String(), nullable=False),
    sa.Column('league', sa.String(), nullable=False),
    sa.Column('kickoff_time', sa.DateTime(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('odds_snapshot', sa.JSON(), nullable=True),
    sa.Column('injury_snapshot', sa.JSON(), nullable=True),
    sa.Column('source_quality', sa.Float(), nullable=True),
    sa.Column('pipeline_version', sa.String(), nullable=True),
    sa.Column('is_stale', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feature_store_league_kickoff', 'match_feature_store', ['league', 'kickoff_time'], unique=False)
    op.create_index(op.f('ix_match_feature_store_id'), 'match_feature_store', ['id'], unique=False)
    op.create_index(op.f('ix_match_feature_store_league'), 'match_feature_store', ['league'], unique=False)
    op.create_index(op.f('ix_match_feature_store_match_id'), 'match_feature_store', ['match_id'], unique=True)
    op.create_table('model_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('model_type', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('accuracy_1x2', sa.Float(), nullable=True),
    sa.Column('accuracy_ou', sa.Float(), nullable=True),
    sa.Column('brier_score', sa.Float(), nullable=True),
    sa.Column('log_loss', sa.Float(), nullable=True),
    sa.Column('predictions_total', sa.Integer(), nullable=True),
    sa.Column('predictions_correct', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('pkl_loaded', sa.Boolean(), nullable=True),
    sa.Column('pkl_path', sa.String(length=512), nullable=True),
    sa.Column('training_samples', sa.Integer(), nullable=True),
    sa.Column('supported_markets', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', name='uq_model_metadata_key')
    )
    op.create_index(op.f('ix_model_metadata_id'), 'model_metadata', ['id'], unique=False)
    op.create_index(op.f('ix_model_metadata_key'), 'model_metadata', ['key'], unique=True)
    op.create_table('oracle_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('match_id', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=False),
    sa.Column('away_score', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=10), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_accepted', sa.Boolean(), nullable=False),
    sa.Column('dispute_flag', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'source', name='uq_oracle_match_source')
    )
    op.create_index('idx_oracle_dispute', 'oracle_results', ['dispute_flag'], unique=False)
    op.create_index('idx_oracle_match_id', 'oracle_results', ['match_id'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('leagues_processed', sa.JSON(), nullable=True),
    sa.Column('matches_upserted', sa.Integer(), nullable=True),
    sa.Column('matches_skipped', sa.Integer(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_runs_id'), 'pipeline_runs', ['id'], unique=False)
    op.create_table('subscription_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('price_monthly', sa.Float(), nullable=True),
    sa.Column('price_yearly', sa.Float(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('prediction_limit', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_subscription_plans_id'), 'subscription_plans', ['id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('league', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('short_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_teams_external_id', 'teams', ['external_id'], unique=False)
    op.create_index('idx_teams_name', 'teams', ['name'], unique=False)
    op.create_index(op.f('ix_teams_external_id'), 'teams', ['external_id'], unique=False)
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=False)
    op.create_table('training_datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=True),
    sa.Column('leagues', sa.JSON(), nullable=True),
    sa.Column('date_range_start', sa.String(length=20), nullable=True),
    sa.Column('date_range_end', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=100), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_datasets_id'), 'training_datasets', ['id'], unique=False)
    op.create_table('user_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_key_hash', sa.String(length=64), nullable=False),
    sa.Column('plan_name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=100), nullable=True),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('prediction_count_today', sa.Integer(), nullable=True),
    sa.Column('prediction_count_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_subscriptions_api_key_hash'), 'user_subscriptions', ['api_key_hash'], unique=True)
    op.create_index(op.f('ix_user_subscriptions_id'), 'user_subscriptions', ['id'], unique=False)
    op.create_table('vitcoin_price_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('price_usd', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('circulating_supply', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('rolling_revenue_usd', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_vitcoin_price_calculated_at', 'vitcoin_price_history', ['calculated_at'], unique=False)
    op.create_table('wallet_subscription_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('price_ngn', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_usdt', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_pi', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_vitcoin', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('bridge_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tx_hash', sa.String(length=128), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('amount_in', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('amount_out', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('fee', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('destination_address', sa.String(length=255), nullable=False),
    sa.Column('source_address', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('status_message', sa.Text(), nullable=True),
    sa.Column('relayer_tx_hash', sa.String(length=128), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['bridge_pools.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bridge_tx_created_at', 'bridge_transactions', ['created_at'], unique=False)
    op.create_index('idx_bridge_tx_status', 'bridge_transactions', ['status'], unique=False)
    op.create_index('idx_bridge_tx_user_id', 'bridge_transactions', ['user_id'], unique=False)
    op.create_index(op.f('ix_bridge_transactions_id'), 'bridge_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_bridge_transactions_pool_id'), 'bridge_transactions', ['pool_id'], unique=False)
    op.create_index(op.f('ix_bridge_transactions_tx_hash'), 'bridge_transactions', ['tx_hash'], unique=True)
    op.create_index(op.f('ix_bridge_transactions_user_id'), 'bridge_transactions', ['user_id'], unique=False)
    op.create_table('dev_api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('key_prefix', sa.String(length=12), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('key_plain', sa.String(length=64), nullable=True),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('rate_limit_rpm', sa.Integer(), nullable=False),
    sa.Column('rate_limit_rpd', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('total_vitcoin_billed', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index('idx_dev_key_is_active', 'dev_api_keys', ['is_active'], unique=False)
    op.create_index('idx_dev_key_prefix', 'dev_api_keys', ['key_prefix'], unique=False)
    op.create_index('idx_dev_key_user_id', 'dev_api_keys', ['user_id'], unique=False)
    op.create_index(op.f('ix_dev_api_keys_id'), 'dev_api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_dev_api_keys_user_id'), 'dev_api_keys', ['user_id'], unique=False)
    op.create_table('fraud_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('flagged_by', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('rule_code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('evidence_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_flag_category', 'fraud_flags', ['category'], unique=False)
    op.create_index('idx_flag_created', 'fraud_flags', ['created_at'], unique=False)
    op.create_index('idx_flag_severity', 'fraud_flags', ['severity'], unique=False)
    op.create_index('idx_flag_status', 'fraud_flags', ['status'], unique=False)
    op.create_index('idx_flag_user_id', 'fraud_flags', ['user_id'], unique=False)
    op.create_index(op.f('ix_fraud_flags_id'), 'fraud_flags', ['id'], unique=False)
    op.create_index(op.f('ix_fraud_flags_user_id'), 'fraud_flags', ['user_id'], unique=False)
    op.create_table('gov_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('data_type', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_gov_configs_id'), 'gov_configs', ['id'], unique=False)
    op.create_table('gov_proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposer_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('change_payload', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('voting_starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voting_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timelock_seconds', sa.Integer(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_note', sa.Text(), nullable=True),
    sa.Column('votes_for', sa.Float(), nullable=False),
    sa.Column('votes_against', sa.Float(), nullable=False),
    sa.Column('votes_abstain', sa.Float(), nullable=False),
    sa.Column('quorum_required', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['proposer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_gov_proposal_proposer_id', 'gov_proposals', ['proposer_id'], unique=False)
    op.create_index('idx_gov_proposal_status', 'gov_proposals', ['status'], unique=False)
    op.create_index(op.f('ix_gov_proposals_id'), 'gov_proposals', ['id'], unique=False)
    op.create_index(op.f('ix_gov_proposals_proposer_id'), 'gov_proposals', ['proposer_id'], unique=False)
    op.create_table('marketplace_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('price_per_call', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('model_key', sa.String(length=64), nullable=True),
    sa.Column('total_revenue', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('creator_revenue', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('protocol_revenue', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('rating_sum', sa.Float(), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_listing_category', 'marketplace_listings', ['category'], unique=False)
    op.create_index('idx_listing_creator_id', 'marketplace_listings', ['creator_id'], unique=False)
    op.create_index('idx_listing_is_active', 'marketplace_listings', ['is_active'], unique=False)
    op.create_index(op.f('ix_marketplace_listings_creator_id'), 'marketplace_listings', ['creator_id'], unique=False)
    op.create_index(op.f('ix_marketplace_listings_id'), 'marketplace_listings', ['id'], unique=False)
    op.create_index(op.f('ix_marketplace_listings_slug'), 'marketplace_listings', ['slug'], unique=True)
    op.create_table('match_settlements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('match_id', sa.String(length=100), nullable=False),
    sa.Column('consensus_id', sa.String(length=36), nullable=False),
    sa.Column('oracle_result', sa.String(length=10), nullable=False),
    sa.Column('total_pool', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('winning_pool', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('validator_fund', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('treasury_fund', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('burn_amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('ai_fund', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['consensus_id'], ['consensus_predictions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id')
    )
    op.create_index('idx_settlement_match_id', 'match_settlements', ['match_id'], unique=False)
    op.create_table('module_training_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('league', sa.String(length=100), nullable=False),
    sa.Column('team_filter', sa.String(length=200), nullable=True),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('column_profile', sa.JSON(), nullable=True),
    sa.Column('quality_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('quality_breakdown', sa.JSON(), nullable=True),
    sa.Column('generated_prompt', sa.Text(), nullable=True),
    sa.Column('vitcoin_reward', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('vitcoin_earned', sa.Boolean(), nullable=False),
    sa.Column('model_accuracy', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('improvement_suggestion', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_module_tj_status', 'module_training_jobs', ['status'], unique=False)
    op.create_index('idx_module_tj_submitted_at', 'module_training_jobs', ['submitted_at'], unique=False)
    op.create_index('idx_module_tj_user_id', 'module_training_jobs', ['user_id'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('prediction_alerts', sa.Boolean(), nullable=False),
    sa.Column('match_results', sa.Boolean(), nullable=False),
    sa.Column('wallet_activity', sa.Boolean(), nullable=False),
    sa.Column('validator_rewards', sa.Boolean(), nullable=False),
    sa.Column('subscription_expiry', sa.Boolean(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('telegram_enabled', sa.Boolean(), nullable=False),
    sa.Column('in_app_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_notification_preferences_id'), 'notification_preferences', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('PREDICTION_ALERT', 'MATCH_RESULT', 'WALLET_ACTIVITY', 'VALIDATOR_REWARD', 'SUBSCRIPTION_EXPIRY', 'SYSTEM', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('channel', sa.Enum('IN_APP', 'WEBSOCKET', 'EMAIL', 'TELEGRAM', name='notificationchannel'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('platform_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('risk_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rule_code', sa.String(length=64), nullable=False),
    sa.Column('score_impact', sa.Float(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('evidence_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_risk_event_created', 'risk_events', ['created_at'], unique=False)
    op.create_index('idx_risk_event_rule', 'risk_events', ['rule_code'], unique=False)
    op.create_index('idx_risk_event_user', 'risk_events', ['user_id'], unique=False)
    op.create_index(op.f('ix_risk_events_id'), 'risk_events', ['id'], unique=False)
    op.create_index(op.f('ix_risk_events_rule_code'), 'risk_events', ['rule_code'], unique=False)
    op.create_index(op.f('ix_risk_events_user_id'), 'risk_events', ['user_id'], unique=False)
    op.create_table('user_stakes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.String(length=100), nullable=False),
    sa.Column('prediction', sa.String(length=10), nullable=False),
    sa.Column('stake_amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payout_amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_stake_match_id', 'user_stakes', ['match_id'], unique=False)
    op.create_index('idx_stake_status', 'user_stakes', ['status'], unique=False)
    op.create_index('idx_stake_user_id', 'user_stakes', ['user_id'], unique=False)
    op.create_table('user_trust_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('transaction_score', sa.Float(), nullable=False),
    sa.Column('prediction_score', sa.Float(), nullable=False),
    sa.Column('activity_score', sa.Float(), nullable=False),
    sa.Column('fraud_penalty', sa.Float(), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('risk_tier', sa.String(length=16), nullable=False),
    sa.Column('total_flags', sa.Integer(), nullable=False),
    sa.Column('open_flags', sa.Integer(), nullable=False),
    sa.Column('last_calculated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trust_composite', 'user_trust_scores', ['composite_score'], unique=False)
    op.create_index('idx_trust_tier', 'user_trust_scores', ['risk_tier'], unique=False)
    op.create_index(op.f('ix_user_trust_scores_id'), 'user_trust_scores', ['id'], unique=False)
    op.create_index(op.f('ix_user_trust_scores_user_id'), 'user_trust_scores', ['user_id'], unique=True)
    op.create_table('validator_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stake_amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('trust_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('total_predictions', sa.Integer(), nullable=False),
    sa.Column('accurate_predictions', sa.Integer(), nullable=False),
    sa.Column('influence_score', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_active', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_validator_status', 'validator_profiles', ['status'], unique=False)
    op.create_index('idx_validator_trust_score', 'validator_profiles', ['trust_score'], unique=False)
    op.create_index('idx_validator_user_id', 'validator_profiles', ['user_id'], unique=False)
    op.create_table('wallets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ngn_balance', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('usd_balance', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('usdt_balance', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('pi_balance', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('vitcoin_balance', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('is_frozen', sa.Boolean(), nullable=False),
    sa.Column('kyc_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_wallets_is_frozen', 'wallets', ['is_frozen'], unique=False)
    op.create_index('idx_wallets_user_id', 'wallets', ['user_id'], unique=False)
    op.create_table('bridge_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['bridge_transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bridge_audit_logs_id'), 'bridge_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_bridge_audit_logs_transaction_id'), 'bridge_audit_logs', ['transaction_id'], unique=False)
    op.create_table('dev_api_usage_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('vitcoin_billed', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('called_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['dev_api_keys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dev_usage_called_at', 'dev_api_usage_logs', ['called_at'], unique=False)
    op.create_index('idx_dev_usage_key_id', 'dev_api_usage_logs', ['api_key_id'], unique=False)
    op.create_index('idx_dev_usage_user_id', 'dev_api_usage_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_dev_api_usage_logs_api_key_id'), 'dev_api_usage_logs', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_dev_api_usage_logs_id'), 'dev_api_usage_logs', ['id'], unique=False)
    op.create_index(op.f('ix_dev_api_usage_logs_user_id'), 'dev_api_usage_logs', ['user_id'], unique=False)
    op.create_table('gov_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('voter_id', sa.Integer(), nullable=False),
    sa.Column('choice', sa.String(length=10), nullable=False),
    sa.Column('voting_power', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('voted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['gov_proposals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proposal_id', 'voter_id', name='uq_gov_vote_proposal_voter')
    )
    op.create_index('idx_gov_vote_proposal_id', 'gov_votes', ['proposal_id'], unique=False)
    op.create_index('idx_gov_vote_voter_id', 'gov_votes', ['voter_id'], unique=False)
    op.create_index(op.f('ix_gov_votes_id'), 'gov_votes', ['id'], unique=False)
    op.create_index(op.f('ix_gov_votes_proposal_id'), 'gov_votes', ['proposal_id'], unique=False)
    op.create_index(op.f('ix_gov_votes_voter_id'), 'gov_votes', ['voter_id'], unique=False)
    op.create_table('marketplace_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['marketplace_listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id', 'user_id', name='uq_rating_listing_user')
    )
    op.create_index('idx_rating_listing_id', 'marketplace_ratings', ['listing_id'], unique=False)
    op.create_index(op.f('ix_marketplace_ratings_id'), 'marketplace_ratings', ['id'], unique=False)
    op.create_index(op.f('ix_marketplace_ratings_listing_id'), 'marketplace_ratings', ['listing_id'], unique=False)
    op.create_index(op.f('ix_marketplace_ratings_user_id'), 'marketplace_ratings', ['user_id'], unique=False)
    op.create_table('marketplace_usage_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('caller_id', sa.Integer(), nullable=False),
    sa.Column('vitcoin_charged', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('creator_share', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('protocol_share', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('input_summary', sa.Text(), nullable=True),
    sa.Column('output_summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('called_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['caller_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['marketplace_listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_usage_called_at', 'marketplace_usage_logs', ['called_at'], unique=False)
    op.create_index('idx_usage_caller_id', 'marketplace_usage_logs', ['caller_id'], unique=False)
    op.create_index('idx_usage_listing_id', 'marketplace_usage_logs', ['listing_id'], unique=False)
    op.create_index(op.f('ix_marketplace_usage_logs_caller_id'), 'marketplace_usage_logs', ['caller_id'], unique=False)
    op.create_index(op.f('ix_marketplace_usage_logs_id'), 'marketplace_usage_logs', ['id'], unique=False)
    op.create_index(op.f('ix_marketplace_usage_logs_listing_id'), 'marketplace_usage_logs', ['listing_id'], unique=False)
    op.create_table('module_training_guide_steps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('required_columns', sa.JSON(), nullable=True),
    sa.Column('example_data', sa.JSON(), nullable=True),
    sa.Column('tips', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['module_training_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_module_tgs_job_id', 'module_training_guide_steps', ['job_id'], unique=False)
    op.create_table('validator_predictions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('validator_id', sa.String(length=36), nullable=False),
    sa.Column('match_id', sa.String(length=100), nullable=False),
    sa.Column('p_home', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('p_draw', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('p_away', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('trust_delta', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('reward_earned', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.ForeignKeyConstraint(['validator_id'], ['validator_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('validator_id', 'match_id', name='uq_validator_match_prediction')
    )
    op.create_index('idx_val_pred_match_id', 'validator_predictions', ['match_id'], unique=False)
    op.create_index('idx_val_pred_validator_id', 'validator_predictions', ['validator_id'], unique=False)
    op.create_table('wallet_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('rate_snapshot', sa.JSON(), nullable=True),
    sa.Column('fee_amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('fee_currency', sa.String(length=10), nullable=True),
    sa.Column('tx_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference', name='uq_wallet_transactions_reference')
    )
    op.create_index('idx_wallet_tx_created_at', 'wallet_transactions', ['created_at'], unique=False)
    op.create_index('idx_wallet_tx_currency', 'wallet_transactions', ['currency'], unique=False)
    op.create_index('idx_wallet_tx_status', 'wallet_transactions', ['status'], unique=False)
    op.create_index('idx_wallet_tx_type', 'wallet_transactions', ['type'], unique=False)
    op.create_index('idx_wallet_tx_user_id', 'wallet_transactions', ['user_id'], unique=False)
    op.create_index('idx_wallet_tx_wallet_id', 'wallet_transactions', ['wallet_id'], unique=False)
    op.create_table('withdrawal_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.String(length=36), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('destination_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('auto_approved', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_withdrawal_requested_at', 'withdrawal_requests', ['requested_at'], unique=False)
    op.create_index('idx_withdrawal_status', 'withdrawal_requests', ['status'], unique=False)
    op.create_index('idx_withdrawal_user_id', 'withdrawal_requests', ['user_id'], unique=False)
    op.create_table('wallet_user_subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('currency_paid', sa.String(length=10), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('renewal_tx_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['wallet_subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['renewal_tx_id'], ['wallet_transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_wallet_subs_expires_at', 'wallet_user_subscriptions', ['expires_at'], unique=False)
    op.create_index('idx_wallet_subs_status', 'wallet_user_subscriptions', ['status'], unique=False)
    op.create_index('idx_wallet_subs_user_id', 'wallet_user_subscriptions', ['user_id'], unique=False)
    op.create_index(op.f('ix_ai_performances_id'), 'ai_performances', ['id'], unique=False)
    op.create_index('idx_ai_predictions_match', 'ai_predictions', ['match_id'], unique=False)
    op.create_index('idx_ai_predictions_source', 'ai_predictions', ['source'], unique=False)
    op.create_index(op.f('ix_ai_predictions_id'), 'ai_predictions', ['id'], unique=False)
    op.create_index(op.f('ix_ai_signal_cache_id'), 'ai_signal_cache', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_signal_cache_id'), table_name='ai_signal_cache')
    op.drop_index(op.f('ix_ai_predictions_id'), table_name='ai_predictions')
    op.drop_index('idx_ai_predictions_source', table_name='ai_predictions')
    op.drop_index('idx_ai_predictions_match', table_name='ai_predictions')
    op.drop_index(op.f('ix_ai_performances_id'), table_name='ai_performances')
    op.drop_index('idx_wallet_subs_user_id', table_name='wallet_user_subscriptions')
    op.drop_index('idx_wallet_subs_status', table_name='wallet_user_subscriptions')
    op.drop_index('idx_wallet_subs_expires_at', table_name='wallet_user_subscriptions')
    op.drop_table('wallet_user_subscriptions')
    op.drop_index('idx_withdrawal_user_id', table_name='withdrawal_requests')
    op.drop_index('idx_withdrawal_status', table_name='withdrawal_requests')
    op.drop_index('idx_withdrawal_requested_at', table_name='withdrawal_requests')
    op.drop_table('withdrawal_requests')
    op.drop_index('idx_wallet_tx_wallet_id', table_name='wallet_transactions')
    op.drop_index('idx_wallet_tx_user_id', table_name='wallet_transactions')
    op.drop_index('idx_wallet_tx_type', table_name='wallet_transactions')
    op.drop_index('idx_wallet_tx_status', table_name='wallet_transactions')
    op.drop_index('idx_wallet_tx_currency', table_name='wallet_transactions')
    op.drop_index('idx_wallet_tx_created_at', table_name='wallet_transactions')
    op.drop_table('wallet_transactions')
    op.drop_index('idx_val_pred_validator_id', table_name='validator_predictions')
    op.drop_index('idx_val_pred_match_id', table_name='validator_predictions')
    op.drop_table('validator_predictions')
    op.drop_index('idx_module_tgs_job_id', table_name='module_training_guide_steps')
    op.drop_table('module_training_guide_steps')
    op.drop_index(op.f('ix_marketplace_usage_logs_listing_id'), table_name='marketplace_usage_logs')
    op.drop_index(op.f('ix_marketplace_usage_logs_id'), table_name='marketplace_usage_logs')
    op.drop_index(op.f('ix_marketplace_usage_logs_caller_id'), table_name='marketplace_usage_logs')
    op.drop_index('idx_usage_listing_id', table_name='marketplace_usage_logs')
    op.drop_index('idx_usage_caller_id', table_name='marketplace_usage_logs')
    op.drop_index('idx_usage_called_at', table_name='marketplace_usage_logs')
    op.drop_table('marketplace_usage_logs')
    op.drop_index(op.f('ix_marketplace_ratings_user_id'), table_name='marketplace_ratings')
    op.drop_index(op.f('ix_marketplace_ratings_listing_id'), table_name='marketplace_ratings')
    op.drop_index(op.f('ix_marketplace_ratings_id'), table_name='marketplace_ratings')
    op.drop_index('idx_rating_listing_id', table_name='marketplace_ratings')
    op.drop_table('marketplace_ratings')
    op.drop_index(op.f('ix_gov_votes_voter_id'), table_name='gov_votes')
    op.drop_index(op.f('ix_gov_votes_proposal_id'), table_name='gov_votes')
    op.drop_index(op.f('ix_gov_votes_id'), table_name='gov_votes')
    op.drop_index('idx_gov_vote_voter_id', table_name='gov_votes')
    op.drop_index('idx_gov_vote_proposal_id', table_name='gov_votes')
    op.drop_table('gov_votes')
    op.drop_index(op.f('ix_dev_api_usage_logs_user_id'), table_name='dev_api_usage_logs')
    op.drop_index(op.f('ix_dev_api_usage_logs_id'), table_name='dev_api_usage_logs')
    op.drop_index(op.f('ix_dev_api_usage_logs_api_key_id'), table_name='dev_api_usage_logs')
    op.drop_index('idx_dev_usage_user_id', table_name='dev_api_usage_logs')
    op.drop_index('idx_dev_usage_key_id', table_name='dev_api_usage_logs')
    op.drop_index('idx_dev_usage_called_at', table_name='dev_api_usage_logs')
    op.drop_table('dev_api_usage_logs')
    op.drop_index(op.f('ix_bridge_audit_logs_transaction_id'), table_name='bridge_audit_logs')
    op.drop_index(op.f('ix_bridge_audit_logs_id'), table_name='bridge_audit_logs')
    op.drop_table('bridge_audit_logs')
    op.drop_index('idx_wallets_user_id', table_name='wallets')
    op.drop_index('idx_wallets_is_frozen', table_name='wallets')
    op.drop_table('wallets')
    op.drop_index('idx_validator_user_id', table_name='validator_profiles')
    op.drop_index('idx_validator_trust_score', table_name='validator_profiles')
    op.drop_index('idx_validator_status', table_name='validator_profiles')
    op.drop_table('validator_profiles')
    op.drop_index(op.f('ix_user_trust_scores_user_id'), table_name='user_trust_scores')
    op.drop_index(op.f('ix_user_trust_scores_id'), table_name='user_trust_scores')
    op.drop_index('idx_trust_tier', table_name='user_trust_scores')
    op.drop_index('idx_trust_composite', table_name='user_trust_scores')
    op.drop_table('user_trust_scores')
    op.drop_index('idx_stake_user_id', table_name='user_stakes')
    op.drop_index('idx_stake_status', table_name='user_stakes')
    op.drop_index('idx_stake_match_id', table_name='user_stakes')
    op.drop_table('user_stakes')
    op.drop_index(op.f('ix_risk_events_user_id'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_rule_code'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_id'), table_name='risk_events')
    op.drop_index('idx_risk_event_user', table_name='risk_events')
    op.drop_index('idx_risk_event_rule', table_name='risk_events')
    op.drop_index('idx_risk_event_created', table_name='risk_events')
    op.drop_table('risk_events')
    op.drop_table('platform_configs')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_notification_preferences_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index('idx_module_tj_user_id', table_name='module_training_jobs')
    op.drop_index('idx_module_tj_submitted_at', table_name='module_training_jobs')
    op.drop_index('idx_module_tj_status', table_name='module_training_jobs')
    op.drop_table('module_training_jobs')
    op.drop_index('idx_settlement_match_id', table_name='match_settlements')
    op.drop_table('match_settlements')
    op.drop_index(op.f('ix_marketplace_listings_slug'), table_name='marketplace_listings')
    op.drop_index(op.f('ix_marketplace_listings_id'), table_name='marketplace_listings')
    op.drop_index(op.f('ix_marketplace_listings_creator_id'), table_name='marketplace_listings')
    op.drop_index('idx_listing_is_active', table_name='marketplace_listings')
    op.drop_index('idx_listing_creator_id', table_name='marketplace_listings')
    op.drop_index('idx_listing_category', table_name='marketplace_listings')
    op.drop_table('marketplace_listings')
    op.drop_index(op.f('ix_gov_proposals_proposer_id'), table_name='gov_proposals')
    op.drop_index(op.f('ix_gov_proposals_id'), table_name='gov_proposals')
    op.drop_index('idx_gov_proposal_status', table_name='gov_proposals')
    op.drop_index('idx_gov_proposal_proposer_id', table_name='gov_proposals')
    op.drop_table('gov_proposals')
    op.drop_index(op.f('ix_gov_configs_id'), table_name='gov_configs')
    op.drop_table('gov_configs')
    op.drop_index(op.f('ix_fraud_flags_user_id'), table_name='fraud_flags')
    op.drop_index(op.f('ix_fraud_flags_id'), table_name='fraud_flags')
    op.drop_index('idx_flag_user_id', table_name='fraud_flags')
    op.drop_index('idx_flag_status', table_name='fraud_flags')
    op.drop_index('idx_flag_severity', table_name='fraud_flags')
    op.drop_index('idx_flag_created', table_name='fraud_flags')
    op.drop_index('idx_flag_category', table_name='fraud_flags')
    op.drop_table('fraud_flags')
    op.drop_index(op.f('ix_dev_api_keys_user_id'), table_name='dev_api_keys')
    op.drop_index(op.f('ix_dev_api_keys_id'), table_name='dev_api_keys')
    op.drop_index('idx_dev_key_user_id', table_name='dev_api_keys')
    op.drop_index('idx_dev_key_prefix', table_name='dev_api_keys')
    op.drop_index('idx_dev_key_is_active', table_name='dev_api_keys')
    op.drop_table('dev_api_keys')
    op.drop_index(op.f('ix_bridge_transactions_user_id'), table_name='bridge_transactions')
    op.drop_index(op.f('ix_bridge_transactions_tx_hash'), table_name='bridge_transactions')
    op.drop_index(op.f('ix_bridge_transactions_pool_id'), table_name='bridge_transactions')
    op.drop_index(op.f('ix_bridge_transactions_id'), table_name='bridge_transactions')
    op.drop_index('idx_bridge_tx_user_id', table_name='bridge_transactions')
    op.drop_index('idx_bridge_tx_status', table_name='bridge_transactions')
    op.drop_index('idx_bridge_tx_created_at', table_name='bridge_transactions')
    op.drop_table('bridge_transactions')
    op.drop_table('wallet_subscription_plans')
    op.drop_index('idx_vitcoin_price_calculated_at', table_name='vitcoin_price_history')
    op.drop_table('vitcoin_price_history')
    op.drop_index(op.f('ix_user_subscriptions_id'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_api_key_hash'), table_name='user_subscriptions')
    op.drop_table('user_subscriptions')
    op.drop_index(op.f('ix_training_datasets_id'), table_name='training_datasets')
    op.drop_table('training_datasets')
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_external_id'), table_name='teams')
    op.drop_index('idx_teams_name', table_name='teams')
    op.drop_index('idx_teams_external_id', table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_subscription_plans_id'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_pipeline_runs_id'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index('idx_oracle_match_id', table_name='oracle_results')
    op.drop_index('idx_oracle_dispute', table_name='oracle_results')
    op.drop_table('oracle_results')
    op.drop_index(op.f('ix_model_metadata_key'), table_name='model_metadata')
    op.drop_index(op.f('ix_model_metadata_id'), table_name='model_metadata')
    op.drop_table('model_metadata')
    op.drop_index(op.f('ix_match_feature_store_match_id'), table_name='match_feature_store')
    op.drop_index(op.f('ix_match_feature_store_league'), table_name='match_feature_store')
    op.drop_index(op.f('ix_match_feature_store_id'), table_name='match_feature_store')
    op.drop_index('ix_feature_store_league_kickoff', table_name='match_feature_store')
    op.drop_table('match_feature_store')
    op.drop_index(op.f('ix_dev_api_plans_id'), table_name='dev_api_plans')
    op.drop_table('dev_api_plans')
    op.drop_index(op.f('ix_decision_logs_prediction_id'), table_name='decision_logs')
    op.drop_index(op.f('ix_decision_logs_match_id'), table_name='decision_logs')
    op.drop_index(op.f('ix_decision_logs_id'), table_name='decision_logs')
    op.drop_index('idx_decision_logs_match', table_name='decision_logs')
    op.drop_table('decision_logs')
    op.drop_index('idx_consensus_status', table_name='consensus_predictions')
    op.drop_index('idx_consensus_match_id', table_name='consensus_predictions')
    op.drop_table('consensus_predictions')
    op.drop_index(op.f('ix_bridge_pools_id'), table_name='bridge_pools')
    op.drop_index('idx_bridge_pool_assets', table_name='bridge_pools')
    op.drop_table('bridge_pools')
    op.drop_index(op.f('ix_bankroll_states_id'), table_name='bankroll_states')
    op.drop_table('bankroll_states')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index('idx_audit_timestamp', table_name='audit_logs')
    op.drop_index('idx_audit_actor', table_name='audit_logs')
    op.drop_index('idx_audit_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_ai_prediction_audit_match_id'), table_name='ai_prediction_audit')
    op.drop_index(op.f('ix_ai_prediction_audit_id'), table_name='ai_prediction_audit')
    op.drop_table('ai_prediction_audit')
    # ### end Alembic commands ###