"""'
AgentCoordinator v5 — Memory-Optimised Autonomous Swarm'
'
This version implements lazy loading and conditional activation of agents'
to ensure the platform can run on memory-constrained environments (like Render Free).'
'
Usage:'
    coordinator = get_coordinator()'
    coordinator.start()'
    coordinator.status()         # full JSON snapshot'
    coordinator.trigger(name)    # manual agent trigger'
'
Environment Variables:'
    ENABLED_AGENTS: Comma-separated list of agent names to enable.'
                    If unset, a default "core" set is used in production.'
                    Use "all" to enable all agents (memory intensive).'
"""'
'
from __future__ import annotations'
'
import asyncio'
import logging'
import os'
from datetime import datetime, timezone'
from typing import Any, Dict, List, Optional, Type'
'
logger = logging.getLogger(__name__)'
'
_GLOBAL_COORDINATOR: Optional["AgentCoordinator"] = None'
'
'
def get_coordinator() -> "AgentCoordinator":'
    """'
    Return the active agent coordinator.'
'
    Prefers the running SwarmOrchestrator (registered at startup via'
    set_swarm()) because it supervises all 22 agents. Falls back to the'
    legacy AgentCoordinator singleton if the swarm is unavailable.'
    """'
    global _GLOBAL_COORDINATOR'
    # ── Try SwarmOrchestrator first (v7.0 preferred path) ──────────────'
    try:'
        from app.core.swarm_orchestrator import get_swarm'
        swarm = get_swarm()'
        # Wrap SwarmOrchestrator so callers that use AgentCoordinator-style'
        # attribute access (e.g. coordinator._agents) still work.'
        return swarm  # type: ignore[return-value]'
    except (RuntimeError, ModuleNotFoundError, ImportError):'
        pass  # swarm not yet initialised or module missing — fall back below'
'
    # ── Legacy AgentCoordinator fallback ───────────────────────────────'
    if _GLOBAL_COORDINATOR is None:'
        _GLOBAL_COORDINATOR = AgentCoordinator()'
    return _GLOBAL_COORDINATOR'
'
'
class AgentCoordinator:'
    """Central registry and controller for all autonomous agents."""'
'
    def __init__(self) -> None:'
        self._agents: Dict[str, Any] = {}'
        self._agent_classes: Dict[str, Type] = {}'
        self._tasks: List[asyncio.Task] = []'
        self._started_at = datetime.now(timezone.utc)'
'
        # ── Map names to lazy-loaded classes ─────────────────────────────'
        self._register_agent_classes()'
'
        # ── Determine which agents to enable ─────────────────────────────'
        enabled_names = self._get_enabled_agent_names()'
'
        # ── Instantiate enabled agents ──────────────────────────────────'
        for name in enabled_names:'
            if name in self._agent_classes:'
                try:'
                    self._agents[name] = self._agent_classes[name]()'
                    logger.info("[coordinator] instantiated agent: %s", name)'
                except Exception as e:'
                    logger.error("[coordinator] failed to instantiate agent %s: %s", name, e)'
            else:'
                logger.warning("[coordinator] unknown agent requested: %s", name)'
'
        global _GLOBAL_COORDINATOR'
        _GLOBAL_COORDINATOR = self'
        logger.info("[coordinator] initialised with %d agents (out of %d possible)",'
                    len(self._agents), len(self._agent_classes))'
'
    def _register_agent_classes(self) -> None:'
        """Populates _agent_classes with lazy imports to keep memory low."""'
        # This prevents all agent modules from being loaded into RAM at once'
        # if they aren't actually enabled.'
'
        def _get_perf():'
            from app.agents.performance_monitor import PerformanceMonitorAgent'
            return PerformanceMonitorAgent'
        def _get_weight():'
            from app.agents.weight_optimizer import WeightOptimizerAgent'
            return WeightOptimizerAgent'
        def _get_retrain():'
            from app.agents.retrain_trigger import RetrainTriggerAgent'
            return RetrainTriggerAgent'
        def _get_scout():'
            from app.agents.match_scout_agent import MatchScoutAgent'
            return MatchScoutAgent'
        def _get_news():'
            from app.agents.news_sentinel_agent import NewsSentinelAgent'
            return NewsSentinelAgent'
        def _get_anomaly():'
            from app.agents.odds_anomaly_agent import OddsAnomalyAgent'
            return OddsAnomalyAgent'
        def _get_kyc():'
            from app.agents.kyc_screener_agent import KYCScreenerAgent'
            return KYCScreenerAgent'
        def _get_fraud():'
            from app.agents.fraud_review_agent import FraudReviewAgent'
            return FraudReviewAgent'
        def _get_withdrawal():'
            from app.agents.withdrawal_gatekeeper_agent import WithdrawalGatekeeperAgent'
            return WithdrawalGatekeeperAgent'
        def _get_mkt_audit():'
            from app.agents.marketplace_audit_agent import MarketplaceAuditAgent'
            return MarketplaceAuditAgent'
        def _get_promoter():'
            from app.agents.model_promoter_agent import ModelPromoterAgent'
            return ModelPromoterAgent'
        def _get_analytics():'
            from app.agents.analytics_reporter_agent import AnalyticsReporterAgent'
            return AnalyticsReporterAgent'
        def _get_fixture():'
            from app.agents.fixture_gap_agent import FixtureGapAgent'
            return FixtureGapAgent'
        def _get_acc():'
            from app.agents.accumulator_publisher_agent import AccumulatorPublisherAgent'
            return AccumulatorPublisherAgent'
        def _get_rev():'
            from app.agents.revenue_optimizer_agent import RevenueOptimizerAgent'
            return RevenueOptimizerAgent'
        def _get_gov():'
            from app.agents.governance_executor_agent import GovernanceExecutorAgent'
            return GovernanceExecutorAgent'
        def _get_heal():'
            from app.agents.self_healing_agent import SelfHealingAgent'
            return SelfHealingAgent'
        def _get_audit():'
            from app.agents.audit_sentinel_agent import AuditSentinelAgent'
            return AuditSentinelAgent'
        def _get_moderator():'
            from app.agents.prediction_moderator_agent import PredictionModeratorAgent'
            return PredictionModeratorAgent'
        def _get_academic():'
            from app.agents.academic_agent import AcademicAgent'
            return AcademicAgent'
        def _get_tracker():'
            from app.agents.live_match_tracker_agent import LiveMatchTrackerAgent'
            return LiveMatchTrackerAgent'
        def _get_oracle():'
            from app.agents.oracle_node_agent import OracleNodeAgent'
            return OracleNodeAgent'
        def _get_network():'
            from app.agents.network_guardian_agent import NetworkGuardianAgent'
            return NetworkGuardianAgent'
'
        registry = {'
            "academic-tutor":           _get_academic,'
            "performance-monitor":      _get_perf,'
            "weight-optimizer":         _get_weight,'
            "retrain-trigger":          _get_retrain,'
            "match-scout":              _get_scout,'
            "news-sentinel":            _get_news,'
            "odds-anomaly":             _get_anomaly,'
            "kyc-screener":             _get_kyc,'
            "fraud-review":             _get_fraud,'
            "withdrawal-gatekeeper":    _get_withdrawal,'
            "marketplace-audit":        _get_mkt_audit,'
            "model-promoter":           _get_promoter,'
            "analytics-reporter":       _get_analytics,'
            "fixture-gap":              _get_fixture,'
            "accumulator-publisher":    _get_acc,'
            "revenue-optimizer":        _get_rev,'
            "governance-executor":      _get_gov,'
            "self-healing":             _get_heal,'
            "audit-sentinel":           _get_audit,'
            "prediction-moderator":     _get_moderator,'
            "live-match-tracker":       _get_tracker,'
            "oracle-node":              _get_oracle,'
            "network-guardian":         _get_network,'
        }'
'
        for name, getter in registry.items():'
            try:'
                self._agent_classes[name] = getter()'
            except Exception as e:'
                logger.error("[coordinator] Failed to register class for %s: %s", name, e)'
'
    def _get_enabled_agent_names(self) -> List[str]:'
        env_val = os.getenv("ENABLED_AGENTS", "").lower().strip()'
'
        if env_val == "all":'
            return list(self._agent_classes.keys())'
'
        if env_val:'
            return [n.strip() for n in env_val.split(",") if n.strip() in self._agent_classes]'
'
        # Default "Core" set for memory-constrained production environments'
        # Focus on ML health and real-time tracking'
        return ['
            "performance-monitor",'
            "live-match-tracker",'
            "network-guardian",'
            "weight-optimizer",'
            "match-scout",'
            "oracle-node",'
            "kyc-screener",'
            "academic-tutor"'
        ]'
'
    def start(self, task_list: Optional[List[asyncio.Task]] = None) -> List[asyncio.Task]:'
        """Launch all enabled agent loops as asyncio tasks."""'
        for name, agent in self._agents.items():'
            task = asyncio.create_task(agent.loop(), name=f"agent-{name}")'
            self._tasks.append(task)'
            if task_list is not None:'
                task_list.append(task)'
            logger.info("[coordinator] agent task created: %s (node_id=%s)", name, agent.node_id)'
        return self._tasks'
'
    async def stop(self) -> None:'
        for task in self._tasks:'
            task.cancel()'
        if self._tasks:'
            await asyncio.gather(*self._tasks, return_exceptions=True)'
        logger.info("[coordinator] all agent tasks stopped")'
'
    # ── Public API ─────────────────────────────────────────────────────────'
'
    def trigger(self, agent_name: str) -> bool:'
        """Manually trigger an agent's next cycle immediately."""'
        agent = self._agents.get(agent_name)'
        if agent is None:'
            return False'
        agent.trigger()'
        return True'
'
    def get_agent_result(self, agent_name: str) -> Optional[Dict[str, Any]]:'
        """Return the last_result of an agent, or None."""'
        agent = self._agents.get(agent_name)'
        return agent.last_result if agent else None'
'
    def status(self) -> Dict[str, Any]:'
        """Return a full status snapshot of all agents."""'
        return {'
            "coordinator": {'
                "started_at":    self._started_at.isoformat(),'
                "agent_count":   len(self._agents),'
                "running_tasks": sum(1 for t in self._tasks if not t.done()),'
                "enabled_agents": list(self._agents.keys()),'
            },'
            "agents": {name: agent.snapshot() for name, agent in self._agents.items()},'
        }'
'
    def summary(self) -> Dict[str, Any]:'
        """Lightweight summary: one row per agent with key health fields."""'
        rows = []'
        for name, agent in self._agents.items():'
            rows.append({'
                "name":               name,'
                "node_id":            agent.node_id,'
                "status":             agent.status,'
                "run_count":          agent.run_count,'
                "error_count":        agent.error_count,'
                "contribution_count": agent.contribution_count,'
                "contribution_score": round(agent.contribution_score, 2),'
                "last_run_at":        agent.last_run_at.isoformat() if agent.last_run_at else None,'
                "next_run_at":        agent.next_run_at.isoformat() if agent.next_run_at else None,'
                "last_error":         agent.last_error,'
            })'
        return {'
            "started_at": self._started_at.isoformat(),'
            "agents":     rows,'
        }'
'
    def network_summary(self) -> Dict[str, Any]:'
        """Network-focused summary: node IDs, contribution scores, online status."""'
        from datetime import timezone'
        now = datetime.now(timezone.utc)'
        nodes = []'
        for name, agent in self._agents.items():'
            last_run = agent.last_run_at'
            online = ('
                last_run is not None'
                and (now - last_run.replace(tzinfo=timezone.utc)).total_seconds() < agent.interval_seconds * 1.5'
            ) if last_run else False'
            nodes.append({'
                "node_id":            agent.node_id,'
                "name":               name,'
                "status":             agent.status,'
                "online":             online,'
                "contribution_count": agent.contribution_count,'
                "contribution_score": round(agent.contribution_score, 2),'
                "run_count":          agent.run_count,'
                "interval_seconds":   agent.interval_seconds,'
            })'
        total_score = sum(a.contribution_score for a in self._agents.values())'
        return {'
            "total_agents": len(self._agents),'
            "online_agents": sum(1 for n in nodes if n["online"]),'
            "total_contribution_score": round(total_score, 2),'
            "nodes": nodes,'
            "started_at": self._started_at.isoformat(),'
        }'
