# app/core/seeding.py'
from decimal import Decimal'
from typing import List, Dict, Any'
from app.modules.tasks.models import TaskType'
'
PLATFORM_CONFIG_DEFAULTS = ['
    ("fee_rates", {"deposit": 0.01, "withdrawal": 0.02, "conversion": 0.005}, "Platform fee rates"),'
    ("vitcoin_min_stake", {"amount": 10, "validator_min": 100}, "Minimum VITCoin stake amounts"),'
    ("withdrawal_limits", {"daily_usd": 1000, "daily_ngn": 500000, "daily_usdt": 1000}, "Daily withdrawal limits"),'
    ("deposit_limits", {"min_usd": 1, "min_ngn": 500, "max_usd": 10000}, "Deposit limits"),'
    ("vitcoin_supply", {"initial": 1000000, "burned": 0, "reserved": 100000}, "VITCoin supply parameters"),'
    ("platform_treasury", {"address": "vit_treasury_001"}, "Platform treasury wallet reference"),'
    ("exchange_rates", {"usd_ngn": 1580, "usd_pi": 0.5, "usd_usdt": 1.0}, "Fiat/crypto exchange rates"),'
    ("vitcoin_price_formula", {"window_days": 30, "method": "revenue_backed"}, "VITCoin price calculation parameters"),'
    ("vitcoin_price_floor", {"amount": "0.10"}, "Minimum VITCoin price in USD"),'
    ("exchange_rates_usd",'
     {"NGN": 0.000633, "USD": 1.0, "USDT": 1.0, "PI": 0.314159, "VITCoin": 0.10},'
     "Per-currency rate to 1 USD (used by the conversion engine)"),'
    ("conversion_fee_pct", {"value": 0.5}, "Currency conversion fee percentage"),'
    ("league_display_names", {'
        "premier_league": "Premier League",'
        "la_liga": "La Liga",'
        "bundesliga": "Bundesliga",'
        "serie_a": "Serie A",'
        "ligue_1": "Ligue 1",'
        "eredivisie": "Eredivisie",'
        "primeira_liga": "Primeira Liga",'
        "championship": "Championship",'
        "scottish_premiership": "Scottish Premiership",'
        "belgian_pro_league": "Belgian Pro League",'
        "ucl": "Champions League",'
        "uel": "Europa League",'
    }, "Mapping of league keys to display names"),'
    ("competitions_config", {'
        "premier_league": "PL",'
        "la_liga": "PD",'
        "bundesliga": "BL1",'
        "serie_a": "SA",'
        "ligue_1": "FL1",'
        "eredivisie": "DED",'
        "championship": "ELC",'
        "primeira_liga": "PPL",'
    }, "Mapping of internal league keys to Football-Data.org codes"),'
]'
'
SUBSCRIPTION_PLANS = ['
    {'
        "name": "free",'
        "display_name": "Free",'
        "price_monthly": 0.0,'
        "price_yearly": 0.0,'
        "prediction_limit": 5,'
        "features": {'
            "predictions": True,'
            "basic_history": True,'
            "advanced_analytics": False,'
            "ai_insights": False,'
            "accumulator_builder": False,'
            "model_breakdown": False,'
            "telegram_alerts": False,'
            "bankroll_tools": False,'
            "csv_upload": False,'
            "priority_support": False,'
        },'
    },'
    {'
        "name": "pro",'
        "display_name": "Pro",'
        "price_monthly": 49.0,'
        "price_yearly": 490.0,'
        "prediction_limit": 100,'
        "features": {'
            "predictions": True,'
            "basic_history": True,'
            "advanced_analytics": True,'
            "ai_insights": True,'
            "accumulator_builder": True,'
            "model_breakdown": True,'
            "telegram_alerts": True,'
            "bankroll_tools": True,'
            "csv_upload": False,'
            "priority_support": False,'
        },'
    },'
    {'
        "name": "elite",'
        "display_name": "Elite",'
        "price_monthly": 199.0,'
        "price_yearly": 1990.0,'
        "prediction_limit": 1000,'
        "features": {'
            "predictions": True,'
            "basic_history": True,'
            "advanced_analytics": True,'
            "ai_insights": True,'
            "accumulator_builder": True,'
            "model_breakdown": True,'
            "telegram_alerts": True,'
            "bankroll_tools": True,'
            "csv_upload": True,'
            "priority_support": True,'
            "validator_eligibility": True,'
            "revenue_share": True,'
        },'
    },'
]'
'
TASK_CATEGORIES = ['
    {"name": "Prediction", "description": "Tasks related to making and reviewing football predictions", "icon": "target", "color": "blue", "sort_order": 1},'
    {"name": "Social", "description": "Community and referral tasks to grow the VIT network", "icon": "users", "color": "green", "sort_order": 2},'
    {"name": "Learning", "description": "Educational tasks to improve your sports intelligence", "icon": "book-open", "color": "purple", "sort_order": 3},'
]'
'
TASK_DEFINITIONS = ['
    # Prediction tasks'
    {'
        "category_name": "Prediction",'
        "title": "Make Your First Prediction",'
        "description": "Submit your first football match prediction using the VIT AI engine.",'
        "short_description": "Submit a prediction",'
        "task_type": TaskType.ONE_TIME.value,'
        "required_count": 1,'
        "vit_reward": 10,'
        "xp_reward": 50,'
        "icon": "zap",'
        "color": "blue",'
        "sort_order": 1,'
        "is_featured": True,'
        "action_url": "/predict",'
        "action_label": "Predict Now",'
    },'
    {'
        "category_name": "Prediction",'
        "title": "Daily Prediction Streak",'
        "description": "Make at least one prediction every day to maintain your streak and earn daily VIT rewards.",'
        "short_description": "Predict daily",'
        "task_type": TaskType.DAILY.value,'
        "required_count": 1,'
        "max_completions": 365,'
        "reset_period_days": 1,'
        "vit_reward": 5,'
        "xp_reward": 20,'
        "icon": "flame",'
        "color": "orange",'
        "sort_order": 2,'
        "is_featured": True,'
        "action_url": "/predict",'
        "action_label": "Predict Today",'
    },'
    {'
        "category_name": "Prediction",'
        "title": "Prediction Veteran",'
        "description": "Accumulate 50 total predictions across any matches to prove your dedication to sports intelligence.",'
        "short_description": "50 total predictions",'
        "task_type": TaskType.PROGRESS.value,'
        "required_count": 50,'
        "vit_reward": 100,'
        "xp_reward": 500,'
        "icon": "trophy",'
        "color": "yellow",'
        "sort_order": 3,'
        "action_url": "/predict",'
        "action_label": "Predict Now",'
    },'
    # Social tasks'
    {'
        "category_name": "Social",'
        "title": "Complete Your Profile",'
        "description": "Add your username and complete your account profile to unlock full platform features.",'
        "short_description": "Complete profile",'
        "task_type": TaskType.ONE_TIME.value,'
        "required_count": 1,'
        "vit_reward": 15,'
        "xp_reward": 75,'
        "icon": "user-check",'
        "color": "green",'
        "sort_order": 1,'
        "is_featured": True,'
        "action_url": "/profile",'
        "action_label": "Edit Profile",'
    },'
    {'
        "category_name": "Social",'
        "title": "Refer a Friend",'
        "description": "Invite a friend to join VIT Sports Intelligence Network using your referral link.",'
        "short_description": "Refer 1 friend",'
        "task_type": TaskType.PROGRESS.value,'
        "required_count": 1,'
        "max_completions": 50,'
        "vit_reward": 25,'
        "xp_reward": 100,'
        "icon": "share-2",'
        "color": "teal",'
        "sort_order": 2,'
        "action_url": "/referral",'
        "action_label": "Get Referral Link",'
    },'
    # Learning tasks'
    {'
        "category_name": "Learning",'
        "title": "Explore the AI Engine",'
        "description": "Visit the AI Engine dashboard to understand how VIT's 13-model ensemble generates predictions.",'
        "short_description": "Visit AI Engine",'
        "task_type": TaskType.ONE_TIME.value,'
        "required_count": 1,'
        "vit_reward": 5,'
        "xp_reward": 25,'
        "icon": "cpu",'
        "color": "purple",'
        "sort_order": 1,'
        "action_url": "/ai-engine",'
        "action_label": "Explore AI Engine",'
    },'
    {'
        "category_name": "Learning",'
        "title": "Check the Research Terminal",'
        "description": "Run a backtest or EV scan in the Research Terminal to sharpen your edge.",'
        "short_description": "Use Research Terminal",'
        "task_type": TaskType.ONE_TIME.value,'
        "required_count": 1,'
        "vit_reward": 10,'
        "xp_reward": 50,'
        "icon": "bar-chart-2",'
        "color": "indigo",'
        "sort_order": 2,'
        "action_url": "/research",'
        "action_label": "Open Research",'
    },'
    {'
        "category_name": "Learning",'
        "title": "Weekly Learning Badge",'
        "description": "Visit the platform and review at least one AI insight report each week.",'
        "short_description": "Weekly engagement",'
        "task_type": TaskType.WEEKLY.value,'
        "required_count": 1,'
        "max_completions": 52,'
        "reset_period_days": 7,'
        "vit_reward": 8,'
        "xp_reward": 40,'
        "icon": "award",'
        "color": "pink",'
        "sort_order": 3,'
        "action_url": "/dashboard",'
        "action_label": "View Dashboard",'
    },'
]'
